# Generated by Django 3.0.8 on 2021-05-05 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200815_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('u_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_from', to=settings.AUTH_USER_MODEL)),
                ('u_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
