# Generated by Django 3.0.8 on 2021-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
